export const INICIAR_SESION = "INICIAR_SESION"
export const CERRAR_SESION = "CERRAR_SESION"

export const SET_PRODUCTOS_CARRITO = "SET_PRODUCTOS_CARRITO"
export const SET_ACTUALIZAR_CARRITO = "SET_ACTUALIZAR_CARRITO"